INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_flip", "center_crop", "normalize"]

DATASET:
  NAME: "S2RDAMS39"
  SOURCE_DOMAINS: ["synthetic"]
  TARGET_DOMAINS: ["real"]

MODEL:
  BACKBONE:
    NAME: "resnet50"

TEST:
  PER_CLASS_RESULT: True