INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_flip", "normalize"]

DATASET:
  NAME: "ImageCLEF"
  SOURCE_DOMAINS: ["b", "c", "i"]
  TARGET_DOMAINS: ["p"]
# you can modify the code to explore four domains

TRAINER:
  DAMP:
    STRONG_TRANSFORMS: ["random_flip", "randaugment", "normalize"]
    PREC: fp16

MODEL:
  BACKBONE:
    NAME: "RN50"
